services:
  noderef:
    build:
      context: .
    image: noderef:latest
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      DEBUG: "1"
      DATA_DIR: /data
      # Optional web password protection
      # WEB_PASSWORD: "change-me"
      # SERVER_URL: "http://alfresco.local:8080/alfresco"
      # SERVER_NAME: "Alfresco"
      # SERVER_USERNAME: "admin"
      # SERVER_PASSWORD: "admin"
      # SERVER_JSCONSOLE_ENDPOINT: "ootbee/jsconsole"
    volumes:
      - noderef_data:/data
    #networks:
    #  - dev_network

volumes:
  noderef_data:
# networks:
#   dev_network:
#     external: true
